import jsPDF from "jspdf";
import { AuditData } from "../utils/scoring";

export async function generatePDFReport(data: AuditData): Promise<void> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 45, "F");
  doc.setTextColor(103, 232, 249);
  doc.setFontSize(22);
  doc.text("azkal-pulse", 20, 20);
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text("Site Audit Report", 20, 28);
  doc.text(new Date(data.timestamp).toLocaleDateString(), 20, 35);
  doc.setTextColor(200, 200, 200);
  doc.text(data.url, 20, 42);

  // Scores
  let y = 60;
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(16);
  doc.text("Scores", 20, y);
  y += 12;

  const scores = [
    { label: "Performance", score: data.scores.performance },
    { label: "SEO", score: data.scores.seo },
    { label: "Accessibility", score: data.scores.accessibility },
  ];

  doc.setFontSize(12);
  for (const s of scores) {
    const color = getScoreColor(s.score);
    doc.setTextColor(color.r, color.g, color.b);
    doc.text(`${s.label}: ${s.score}/100`, 20, y);
    y += 8;
  }

  // Issues
  y += 8;
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(16);
  doc.text("Issues Found", 20, y);
  y += 10;

  doc.setFontSize(10);
  for (const issue of data.issues) {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    const sevColor =
      issue.severity === "high"
        ? { r: 239, g: 68, b: 68 }
        : issue.severity === "medium"
          ? { r: 234, g: 179, b: 8 }
          : { r: 59, g: 130, b: 246 };

    doc.setTextColor(sevColor.r, sevColor.g, sevColor.b);
    doc.text(`[${issue.severity.toUpperCase()}]`, 20, y);
    doc.setTextColor(60, 60, 60);
    doc.text(issue.message, 50, y);
    doc.setTextColor(140, 140, 140);
    doc.text(issue.category, 160, y);
    y += 7;
  }

  // Footer
  y += 10;
  doc.setTextColor(140, 140, 140);
  doc.setFontSize(8);
  doc.text("Generated by azkal-pulse - https://github.com/Ialkyyyy/azkal-pulse", 20, y);

  doc.save(`audit-report-${new Date(data.timestamp).toISOString().split("T")[0]}.pdf`);
}

function getScoreColor(score: number) {
  if (score >= 90) return { r: 34, g: 197, b: 94 };
  if (score >= 50) return { r: 234, g: 179, b: 8 };
  return { r: 239, g: 68, b: 68 };
}
